version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: blog_mongodb
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - blog_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      MONGODB_DB_NAME: ${MONGO_INITDB_DATABASE}
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - blog_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongo_data:
  mongo_config:


networks:
  blog_network:
    driver: bridge
